# 01 Importing libraries

In [2]:
# Importing libraries
import pandas as pd
import numpy as np
import os

# 02 Importing Dataframes

In [4]:
# Importing products dataframe
path = r'C:\Users\vacgo\Documents\Achievement 4\Instacart Basket Analysis\02 Data'
ords_prods_merge = pd.read_pickle(os.path.join(path, 'Prepared Data', 'ords_prods_merge_latest_20241112.pkl'))

# 03 Following Exercise

In [6]:
# Create subset
df = ords_prods_merge[:1000000]

In [7]:
df.shape

(1000000, 19)

In [8]:
df.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_from_last_order,new_customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,merge_2,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day
0,2539329,1,1,2,8,NaN,True,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2539329,1,1,2,8,NaN,True,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders
2,2539329,1,1,2,8,NaN,True,12427,3,0,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders
3,2539329,1,1,2,8,NaN,True,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders
4,2539329,1,1,2,8,NaN,True,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders

In [9]:
# Group by function
df.groupby('product_name')

In [10]:
# With aggregate
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                14.800024
2                17.091743
3                17.913544
4                17.893092
5                15.214270
6                15.382135
7                17.694027
8                16.458105
9                15.957363
10               20.091818
11               16.482026
12               15.615061
13               16.484023
14               17.524632
15               15.691875
16               18.014071
17               16.150593
18               19.602850
19               17.631340
20               17.138607
21               21.956893

In [11]:
df.groupby('department_id')['order_number'].mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

In [12]:
# Adding more aggregations
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                14.800024   1  99
2                17.091743   1  98
3                17.913544   1  99
4                17.893092   1  99
5                15.214270   1  99
6                15.382135   1  99
7                17.694027   1  99
8                16.458105   1  91
9                15.957363   1  99
10               20.091818   1  99
11               16.482026   1  99
12               15.615061   1  99
13               16.484023   1  99
14               17.524632   1  99
15               15.691875   1  99
16               18.014071   1  99
17               16.150593   1  99
18               19.602850   1  99
19               17.631340   1  99
20               17.138607   1  99
21               21.956893   1  97

In [24]:
# Group by user_id for customer loyalty
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [30]:
ords_prods_merge.tail(60)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_from_last_order,new_customer,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,merge_2,price_range_loc,busiest_day,busiest_days_new,busiest_period_of_day,max_order
32404799,2129269,206209,8,3,17,22.0,False,43961,2,1,Organic Peeled Whole Baby Carrots,123,4,3.8,both,Low-range product,Regularly busy,Slowest days,Average orders,13
32404800,2129269,206209,8,3,17,22.0,False,19348,3,1,Fat Free Milk,84,16,4.6,both,Low-range product,Regularly busy,Slowest days,Average orders,13
32404801,2129269,206209,8,3,17,22.0,False,13176,4,1,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Regularly busy,Slowest days,Average orders,13
32404802,2129269,206209,8,3,17,22.0,False,6846,5,1,Diet Pepsi Pack,77,7,11.3,both,Mid-range product,Regularly busy,Slowest days,Average orders,13
32404803,2129269,206209,8,3,17,22.0,False,17500,6,0,Cinch Sak Extra Large 33 Gallon Trash Bags,60,17,2.1,both,Low-range product,Regularly busy,Slowest days,Average orders,13
32404804,2129269,206209,8,3,17,22.0,False,36056,7,0,Freezer Slider Bags,85,17,13.6,both,Mid-range product,Regularly busy,Slowest days,Average orders,13
32404805,2129269,206209,8,3,17,22.0,False,12376,8,0,Sourdough Demi Baguette,112,3,11.5,both,Mid-range product,Regularly busy,Slowest days,Average orders,13
32404806,2129269,206209,8,3,17,22.0,False,40992,9,1,Chopped Tomatoes,81,15,1.8,both,Low-range product,Regularly busy,Slowest days,Average orders,13
32404807,2129269,206209,8,3,17,22.0,False,33129,10,0,Classic Hummus,67,20,1.3,both,Low-range product,Regularly busy,Slowest days,Average orders,13
32404808,2129269,206209,8,3,17,22.0,False,14870,11,0,Icelandic Style Fat Free Plain Yogurt,120,16,2.1,both,Low-range product,Regularly busy,Slowest days,Average orders,13
32404809,2129269,206209,8,3,17,22.0,False,16066,12,0,Unsalted Tops Saltine Crackers,78,19,7.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,13
32404810,2558525,206209,9,4,15,22.0,False,38167,1,1,Ultra Downy® Clean Breeze™ Liquid Fabric Condi...,75,17,5.8,both,Mid-range product,Least busy,Slowest days,Most orders,13
32404811,2558525,206209,9,4,15,22.0,False,23892,2,1,Original High Efficiency Liquid Laundry Detergent,75,17,9.1,both,Mid-range product,Least busy,Slowest days,Most orders,13
32404812,2558525,206209,9,4,15,22.0,False,6846,3,1,Diet Pepsi Pack,77,7,11.3,both,Mid-range product,Least busy,Slowest days,Most orders,13
32404813,2266710,206209,10,5,18,29.0,False,9405,1,1,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
32404814,2266710,206209,10,5,18,29.0,False,6846,2,1,Diet Pepsi Pack,77,7,11.3,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
32404815,2266710,206209,10,5,18,29.0,False,15700,3,0,Cheddar Cheese Nut Thins Cracker Snacks,78,19,2.3,both,Low-range product,Regularly busy,Regularly busy,Average orders,13
32404816,2266710,206209,10,5,18,29.0,False,26503,4,0,Classic Vegetables Whole Kernel Corn,116,1,6.2,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
32404817,2266710,206209,10,5,18,29.0,False,41213,5,1,French Loaf,112,3,4.8,both,Low-range product,Regularly busy,Regularly busy,Average orders,13
32404818,2266710,206209,10,5,18,29.0,False,23800,6,0,Whole Grain Cereal,121,14,6.2,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
32404819,2266710,206209,10,5,18,29.0,False,24852,7,0,Banana,24,4,12.3,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
32404820,2266710,206209,10,5,18,29.0,False,13838,8,0,Natural Free & Clear Dish Liquid,74,17,3.8,both,Low-range product,Regularly busy,Regularly busy,Average orders,13
32404821,2266710,206209,10,5,18,29.0,False,31130,9,0,Sea Salt Flakes Original,104,13,6.3,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
32404822,1854736,206209,11,4,10,30.0,False,6846,1,1,Diet Pepsi Pack,77,7,11.3,both,Mid-range product,Least busy,Slowest days,Most orders,13
32404823,1854736,206209,11,4,10,30.0,False,9405,2,1,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.5,both,Mid-range product,Least busy,Slowest days,Most orders,13
32404824,1854736,206209,11,4,10,30.0,False,41213,3,1,French Loaf,112,3,4.8,both,Low-range product,Least busy,Slowest days,Most orders,13
32404825,1854736,206209,11,4,10,30.0,False,24852,4,1,Banana,24,4,12.3,both,Mid-range product,Least busy,Slowest days,Most orders,13
32404826,1854736,206209,11,4,10,30.0,False,19348,5,1,Fat Free Milk,84,16,4.6,both,Low-range product,Least busy,Slowest days,Most orders,13
32404827,1854736,206209,11,4,10,30.0,False,15700,6,1,Cheddar Cheese Nut Thins Cracker Snacks,78,19,2.3,both,Low-range product,Least busy,Slowest days,Most orders,13
32404828,1854736,206209,11,4,10,30.0,False,40310,7,0,Oven Roasted Turkey Breast,96,20,1.9,both,Low-range product,Least busy,Slowest days,Most orders,13
32404829,1854736,206209,11,4,10,30.0,False,48370,8,0,Sensitive Toilet Paper,54,17,7.4,both,Mid-range product,Least busy,Slowest days,Most orders,13
32404830,626363,206209,12,1,12,18.0,False,6846,1,1,Diet Pepsi Pack,77,7,11.3,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404831,626363,206209,12,1,12,18.0,False,24852,2,1,Banana,24,4,12.3,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404832,626363,206209,12,1,12,18.0,False,9405,3,1,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.5,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404833,626363,206209,12,1,12,18.0,False,19348,4,1,Fat Free Milk,84,16,4.6,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404834,626363,206209,12,1,12,18.0,False,41213,5,1,French Loaf,112,3,4.8,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404835,626363,206209,12,1,12,18.0,False,15700,6,1,Cheddar Cheese Nut Thins Cracker Snacks,78,19,2.3,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404836,626363,206209,12,1,12,18.0,False,38167,7,1,Ultra Downy® Clean Breeze™ Liquid Fabric Condi...,75,17,5.8,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404837,626363,206209,12,1,12,18.0,False,26209,8,0,Limes,24,4,14.7,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404838,626363,206209,12,1,12,18.0,False,33129,9,1,Classic Hummus,67,20,1.3,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404839,626363,206209,12,1,12,18.0,False,43961,10,1,Organic Peeled Whole Baby Carrots,123,4,3.8,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404840,626363,206209,12,1,12,18.0,False,23800,11,1,Whole Grain Cereal,121,14,6.2,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404841,626363,206209,12,1,12,18.0,False,13838,12,1,Natural Free & Clear Dish Liquid,74,17,3.8,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404842,626363,206209,12,1,12,18.0,False,48742,13,1,Quick 1 Minute Whole Grain Oats,130,14,5.9,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404843,626363,206209,12,1,12,18.0,False,23594,14,1,Medium Salsa,51,13,3.7,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404844,626363,206209,12,1,12,18.0,False,20590,15,0,Disinfecting Wipes Fresh Scent,114,17,5.9,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404845,626363,206209,12,1,12,18.0,False,16168,16,0,Large Organic Omega3 Brown Eggs,86,16,11.8,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404846,626363,206209,12,1,12,18.0,False,33351,17,0,Light Multi-Grain English Muffins,93,3,6.4,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404847,626363,206209,12,1,12,18.0,False,5622,18,0,Cocktail Tomatoes on the Vine,123,4,8.8,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404848,626363,206209,12,1,12,18.0,False,23039,19,1,Fat Free Cream Cheese,108,16,3.4,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404849,626363,206209,12,1,12,18.0,False,14727,20,0,Yellow Onion,123,4,3.2,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404850,2977660,206209,13,1,12,7.0,False,24852,1,1,Banana,24,4,12.3,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404851,2977660,206209,13,1,12,7.0,False,9405,2,1,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.5,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404852,2977660,206209,13,1,12,7.0,False,16168,3,1,Large Organic Omega3 Brown Eggs,86,16,11.8,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404853,2977660,206209,13,1,12,7.0,False,39216,4,0,Original Multigrain Spoonfuls Cereal,121,14,3.3,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404854,2977660,206209,13,1,12,7.0,False,14197,5,1,Tomato Paste,9,9,5.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404855,2977660,206209,13,1,12,7.0,False,38730,6,0,Brownie Crunch High Protein Bar,3,19,5.9,both,Mid-range product,Regularly busy,Busiest days,Most orders,13
32404856,2977660,206209,13,1,12,7.0,False,31477,7,0,High Protein Bar Chunky Peanut Butter,3,19,4.2,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404857,2977660,206209,13,1,12,7.0,False,6567,8,0,Chocolate Peanut Butter Protein Bar,3,19,4.9,both,Low-range product,Regularly busy,Busiest days,Most orders,13
32404858,2977660,206209,13,1,12,7.0,False,22920,9,0,Roasted & Salted Shelled Pistachios,117,19,1.7,both,Low-range product,Regularly busy,Busiest days,Most orders,13

In [36]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [38]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10) , 'loyalty_flag'] = 'Regular customer'

In [44]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [46]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [48]:
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1